# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

encoding: utf-8
timezone: UTC

# Site settings
title: Pat Hermens
email: p@hermens.com.au
description: > # this means to ignore newlines until "baseurl:"
  .Net developer, public speaker, challenge addict, father, husband and (most of all) geek. 
  Interesting problems & inspiring solutions get me out of bed in the morning.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hermens.com.au" # the base hostname & protocol for your site
image: "/assets/img/avatar_bw.webp" # The fallback image used for OG
permalink: /:year/:month/:day/:title/


# Social media usernames for filling out links:
github_username: PHeonix25
# twitter_username: phermens # Fk x.com
linkedin_username: phermens

# Enable posting into the future
future: true

# Be strict about the allowed front-matter
strict_front_matter: true

# Build settings
verbose: true
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: G-V6EFN3GCY3

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# Pagination settings
paginate: 5

# These are the add-ins we want to use
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Parameters required for the comments
emptyArray: []

commenting: open
comments:
  receiver: https://blogcommentsfunc24727.azurewebsites.net/api/PostComment

authors:
  phermens:
    name: Pat Hermens
    email: p@hermens.com.au
    url: https://hermens.com.au

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ext4.vhdx # local development env 

# Provide some defaults, based off path.
defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: phermens
  -
    scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      author: phermens