- Find a theme
    - Start at http://jekyllthemes.org/
    - Clone the repo
- Push to GitHub
    - PARTY
- Configure GitHub 
    - Custom domain (https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/)
- Theme Settings 
    - _config.yml
    - WARN: Root folder
- Template modifications
    - Author information
    - Include files
    - Mod the Template
- Set up Docker
    - inc. the build/deploy scripts
    - WARN: copy the right directory
    - WARN: Adjust locale
- Learn Markdown
- Push posts!
    - TRULY PARTY!