version: '2'
services:
  jekyll:
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --trace --force_polling --watch --config  _config.yml,_config.docker.yml --incremental
    image: jekyll/builder:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000